function [copora_V] = demo_lda()
%   this is a demo of LDA modeling 
%   the demo is a simulation of the experiment displayed in "Finding scientific topics
%   by: T. L. Griffiths, and M. Steyvers In: Proceedings of the National Academy of Sciences, 
%   Vol. 101, Nr. Suppl. 1 (April 2004) , p. 5228-5235."
%   --------------------------------------------------------------
%   author: Hanchen Xiong , University of Innsbruck
%   --------------------------------------------------------------
N_m=200;                 % the number of words in each document
M=100;                   % the number of document
coporal=cell(M,1);       % generated 100 random documents (for visualization)
coporal_V=cell(M,1);     % 100 document with a sequence of words

z_w=zeros(10,25);        % the p(word|topc) with 10 topics and 25 words 
w_position=zeros(25,2);  % the 2D position correspond different indices
% specify word index-position correspondence
% -------------------------------------------------------------
% |  1  |  2  |  3  |  4  |  5  | 
% |  6  |  7  |  8  |  9  |  10 |
% |  11 |  12 |  13 |  14 |  15 |
% |  16 |  17 |  18 |  19 |  20 |
% |  21 |  22 |  23 |  24 |  25 |
%---------------------------------------------------------------
for i=1:5
    for j=1:5
        w_position((i-1)*5+j,1)=i;
        w_position((i-1)*5+j,2)=j;
    end;
end;
   
%---------------------------------------------------------------
% spcify the the p(word|topc) with 10 topics and 25 words
for i=1:5;
    for j=1:5
        z_w(i,i+(j-1)*5)=0.2;
        z_w(i+5,(i-1)*5+j)=0.2;
    end;
end;

%---------------------------------------------------------------
% visualization p(word|topc)
figure(1);
set (gcf,'Position',[200,600,1000,80], 'color','w')
for k=1:10
    topic_matrxi=zeros(5,5);
    for i=1:25
        topic_matrix(w_position(i,1),(w_position(i,2)))=z_w(k,i);
    end;
    subplot(1,10,k); 
    imagesc(topic_matrix);
    colormap('jet');
    axis off;
end;

%---------------------------------------------------------------
% sample M images generated by LDA generative process
alpha=ones(1,10);
for i=1:M
    image=zeros(5,5);
    sequence=zeros(1,N_m);
    pi=sample_dirichlet(alpha);   % sample a pi accordint to p(pi|alpha);
    for n=1:N_m
        k=find(mnrnd(1,pi));         % sample a topic accordtion to pi
        idx=find(mnrnd(1,z_w(k,:)));  % sample a word accordtion to p(word|topic_k)
        x=w_position(idx,1); y=w_position(idx,2);  % find the position of word pp;
        image(x,y)=image(x,y)+1;
        sequence(n)=idx;
    end;
    copora{i,1}=image;
    copora_V{i,1}=sequence;
end;

%---------------------------------------------------------------
% visualization of generated M images
figure(2);
set (gcf,'Position',[200,200,800,950], 'color','w')
for i=1:100
    subplot(10,10,i); 
    imagesc(copora{i,1});
    colormap('jet');
    axis off;
end;

lda_gibbs_sampler(copora_V,10,25);
end

